### ISSUE TITLE
Final set of reproducible significant peaks - encode 3

### ISSUE THREAD

**Issue by gouthamatla** [YeoLab/rbp-maps#8]
Hi All,

May I know where can I find the final set of peak calls from ENCODE 3 RBP data ? I could find individual replicates but I did not find replicate-merged IDR peaks. 

https://www.nature.com/articles/s41586-020-2077-3

Thanks,
Goutham A

**Comment by byee4** [comment]
You can find all reproducible peaks from ENCODE3 on the encodeproject.org site. You may need to convert these to bigBed format to use rbp-maps, but it should be a simple bed -> bigBed conversion.

Here is an example link from the site. If you have any experience parsing out JSON files, I would suggest using their API, otherwise you can use the experiment matrix (ie. 
https://www.encodeproject.org/report/?type=Experiment&control_type!=*&status=released&perturbed=false&assay_title=eCLIP&biosample_ontology.term_name=HepG2&files.file_type=bed+narrowPeak&assembly=hg19
)

example reproducible peaks for RBFOX2 (HepG2):

https://www.encodeproject.org/files/ENCFF871NYM/@@download/ENCFF871NYM.bed.gz

**Comment by gouthamatla** [comment]
Thanks for prompt response. I am looking for the replicate-merged IDR peaks. encode portal has data for individual replicates. The paper mentions that "_Unless otherwise noted, the final set of reproducible and significant peaks was identified by requiring that the replicate-merged peak meet an IDR cutoff of 0.01 as well as P ≤ 0.001 and fold enrichment ≥8 (using the geometric mean of log2(fold enrich- ment) and –log10(P) between the two biological replicates)”_
